### ISSUE TITLE
[버그] Shard 가 적용된 경우 모든 서버수가 입력되지 않음.

### ISSUE THREAD

**Issue by Krchip** [koreanbots/v2-testing#101]
# 버그 설명

Shard 가 적용된 경우 일부봇에서 전체 서버수가 표시되지 않습니다.

# 재현방법

Shard 가 적용된 봇의 페이지로 갑니다 ( 버그 발견 봇은 원더봇 )

해당 봇의 실제 서버수 ( 디스코드 초대링크에 있는 서버 수 기준 ) 와 페이지에 표시되는 서버수를 확인합니다.

# 예상한 동작

실제 서버수와 표시 서버수가 같아야합니다.

# 클라이언트 정보

- 브라우저(버전): Chrome ver. 90.0.4430.93
- OS: Windows 10 20H2 x86
- 기기: Desktop

# 발생되는 페이지

https://beta.koreanbots.dev/bots/wonderbot 등 샤드가 적용된 봇

# 첨부파일

![image](https://user-images.githubusercontent.com/35456778/117935433-ac00a600-b33e-11eb-8969-29d981f61ab0.png)
Koreanbots OBT page

![image](https://user-images.githubusercontent.com/35456778/117935483-b58a0e00-b33e-11eb-80bd-84a0758d8892.png)
Discord invite page

**Comment by minibox24** [comment]
봇 서버수 변경은 해당 봇 개발자의 책임이기에 사이트의 버그가 아니라고 봅니다.

**Comment by simsimler** [comment]
해당 사항은 베타 사이트에는 구 DB가 적용되어 생긴 문제이고, 서버 수는 봇 개발자가 넣기 떄문에 사이트 문제가 아닌 것 같습니다

**Comment by Krchip** [comment]
위에 올려주신 조언 참고해 해당 이슈는 종료토록하겠습니다.

감사합니다.
