### ISSUE TITLE
[버그] 봇 관리페이지에서 선택입력 필드를 빈칸으로 두고 저장할 수 없음

### ISSUE THREAD

**Issue by ArpaAP** [koreanbots/v2-testing#104]
# 버그 설명

봇 관리페이지에서 웹사이트, git 링크 등의 필드를 **빈 상태로 두고** 저장할 시 변경사항이 저장되지 않습니다.

# 재현방법

봇 관리하기(https://beta.koreanbots.dev/manage/봇 아이디) -> 웹사이트 또는 git URL 을 빈칸으로 둠 -> 저장

# 예상한 동작

웹사이트 링크 또는 git 링크가 해제된 상태로 저장되어야 합니다.

# 클라이언트 정보

- 브라우저(버전): Chrome 90.0.4430.212
- OS: Windows 10
- 기기: 해당사항 없음

# 발생되는 페이지

https://beta.koreanbots.dev/manage/751339721782722570

# 첨부파일
...

**Comment by wonderlandpark** [comment]
Can reproduce.
