### ISSUE TITLE
[버그] Missing "Discord Verification" badge on some other Discord bots except "Trusted Bot"

### ISSUE THREAD

**Issue by gunyu1019** [koreanbots/v2-testing#105]
# 버그 설명
<table>
    <thead>
        <tr>
            <th>"KoreanBots 신뢰된 봇", "디스코드 인증"을 둘 다 받은 봇</th>
            <th>"디스코드 인증"만 된 봇</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><img src="https://user-images.githubusercontent.com/16767890/118440399-931f3880-b722-11eb-8e11-b39608279d00.png" /></td>
            <td><img src="https://user-images.githubusercontent.com/16767890/118440564-cf529900-b722-11eb-9e8c-b9cca523da37.png" /></td>
        </tr>
    </tbody>
    <tbody>
        <tr>
            <td><img src="https://user-images.githubusercontent.com/16767890/118440636-ea250d80-b722-11eb-9e62-a52dfa633ca3.png" /></td>
            <td><img src="https://user-images.githubusercontent.com/16767890/118440472-acc08000-b722-11eb-9b64-a2ca6e962dbe.png" /></td>
        </tr>
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <th>"KoreanBots 신뢰된 봇", "디스코드 인증"을 둘 다 받은 봇</th>
            <th>"디스코드 인증"만 된 봇</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><img src="https://user-images.githubusercontent.com/16767890/118437897-6406c800-b71e-11eb-8fe0-0dce47872e1a.png" /></td>
            <td><img src="https://user-images.githubusercontent.com/16767890/118440289-68cd7b00-b722-11eb-84d7-0a420c27609f.png" /></td>
        </tr>
    </tbody>
    <tbody>
        <tr>
            <td><img src="https://user-images.githubusercontent.com/16767890/118437794-3588ed00-b71e-11eb-99cf-534661926987.png" /></td>
            <td><img src="https://user-images.githubusercontent.com/16767890/118437804-39b50a80-b71e-11eb-94b9-6058c53b58ae.png" /></td>
        </tr>
    </tbody>
</table>
첫번째 표는 v1(현재 릴리즈 중인 페이지)를 기준으로, 두번째 표는 v2(베타버전)을 기준으로 찍은 각 봇들 입니다.<br/><br/>
사진을 비교해보면 v2에는 "Koreanbots 신뢰된 봇"에는 "디스코드 봇 인증됨"을 통해 인증 받은 사실이 모두 표시 되어 있으나, "Koreanbots 신뢰된 봇"의 뱃지가 없고 대신 "디스코드 봇 인증됨"만 보유하고 있는 디스코드 봇들에는 반영이 안됬다는 점을 확인 할 수 있습니다. 현재 배포된 웹사이트(v1)를 확인하여 비교해본 결과, 현재 배포되는 웹사이트에서는 모두 "디스코드 봇 인증됨"이라는 뱃지가 달려 있었습니다.

# 재현방법
위 사진을 기준으로 v1(현재 버전)에 있는 "디스코드 봇 인증됨" 뱃지를 받은 봇들에게는 모두 표기되어 있으나, v2(베타 버전)에 있는 봇들에는 "신뢰된 봇"을 제외한 봇들에는, "디스코드 봇 인증됨"이 붙어있지 않습니다.

# 예상한 동작
위 사진에 있는 봇들은 모두 "디스코드 봇 인증됨"이 붙어야 하며, 이외 v1에 있는 "디스코드 봇 인증됨"이라는 뱃지를 가지고 있는 봇들에도 모두 붙어야 합니다.

# 클라이언트 정보

- 브라우저(버전): Chrome 90.0.4430.212
- OS: Windows 10 20H2 빌드 19042
- 기기: Computer(AMD Ryzen 5800X, RAM 32GB(16 x 2EA), RTX 2060 SUPER Founders Edition)

# 발생되는 페이지
https://beta.koreanbots.dev/bots/756792224099991622
https://beta.koreanbots.dev/bots/426722888293548032
https://beta.koreanbots.dev/bots/495209098929766400
https://beta.koreanbots.dev/bots/702661901921943662
외, "디스코드 봇 인증됨"이란 뱃지가 v1에는 붙어있지만 v2에 붙어있지 않는 모든 봇들

# 첨부파일
위에 표를 대신 첨부하였습니다.

**Comment by samsunghappytree123** [comment]
"Koreanbots에서 신뢰하는 봇"의 뱃지는 상단 이름 "옆에" 붙어있으므로 해당 사안은 오류가 아닌 것 같습니다.

**Comment by samsunghappytree123** [comment]
![image](https://user-images.githubusercontent.com/58595445/118442659-d333ea80-b725-11eb-8827-f2098ea9ce2f.jpeg)

**Comment by gunyu1019** [comment]
@samsunghappytree123 제가 말하는 것은 베타버전에는 "디스코드 봇 인증됨"이라는 뱃지가 누락됬다는 것입니다.
"신뢰하는 봇"에만  "디스코드 봇 인증됨"라는 뱃지가 표기되어 있고, 다른 "디스코드 봇 인증됨"가 등록되어야 한다는 봇들에는 등재가 안됬다는 것입니다.

**Comment by samsunghappytree123** [comment]
아 죄송합니다. 대충 읽었네요

**Comment by wonderlandpark** [comment]
Approved, 신뢰됨 플래그로 디스코드 인증됨 마크가 표시되고 있음.
