### ISSUE TITLE
[버그] Wrong flag value contained within beta API

### ISSUE THREAD

**Issue by gunyu1019** [koreanbots/v2-testing#106]
# 버그 설명
![](https://user-images.githubusercontent.com/16767890/118443674-28243080-b727-11eb-8029-0a774ddf68d3.png)
API 내에 있는 flag값이 잘못 표시 됩니다. 버그에 대한 자세한 정보는 아래에 있는 표를 확인해주세요.

# 재현방법
신뢰된 봇들을 API를 통하여 불러오고 flag 값을 확인합니다.

# 예상한 동작
IU봇의 flag값과 달리 전적이와, 치노봇의 flag값은 "한국 디스코드봇 리스트 인증된 봇"과 "디스코드 인증된 봇"의 값이 들어간 (1 << 2 | 1 << 4) = 20 이 반환되어야 합니다.
그러나, "공식봇" 값이 포함되어 (1<<0)이 포함되었습니다 (실제로 21이 반환됨.)

다른 봇들은 정상적으로 작동하나, 신뢰된 봇들의 flag 값이 잘못 설정된 듯 합니다.

# 클라이언트 정보

- 브라우저(버전): Chrome 90.0.4430.212 / Postman for windows Version 8.4.0
- OS: Windows 10 20H2 빌드 19042
- 기기: Computer(AMD Ryzen 5800X, RAM 32GB(16 x 2EA), RTX 2060 SUPER Founders Edtion)

# 발생되는 페이지

https://beta.koreanbots.dev/api/v2/bots/426722888293548032
https://beta.koreanbots.dev/api/v2/bots/756792224099991622

# 첨부파일
* API에서 불러온 값이 작아서 안보일 수 있습니다. 클릭해서 확인해주세요.
<table>
    <tbody>
        <tr>
            <td><img src="https://user-images.githubusercontent.com/16767890/118443345-bfd54f00-b726-11eb-85a1-757488fc57ef.png" /></td>
            <td><img src="https://user-images.githubusercontent.com/16767890/118443493-eabfa300-b726-11eb-87d4-c758ac0ffb90.png" /></td>
            <td><img src="https://user-images.githubusercontent.com/16767890/118443279-aa602500-b726-11eb-89c3-1d273bc1b455.png" /></td>
        </tr>
    </tbody>
    <tbody>
        <tr>
            <td><img src="https://user-images.githubusercontent.com/16767890/118443190-9288a100-b726-11eb-8e51-87eb689f1593.png" /></td>
            <td><img src="https://user-images.githubusercontent.com/16767890/118440399-931f3880-b722-11eb-8e11-b39608279d00.png" /></td>
            <td><img src="https://user-images.githubusercontent.com/16767890/118440636-ea250d80-b722-11eb-9e62-a52dfa633ca3.png" /></td>
        </tr>
    </tbody>
</table>

**Comment by wonderlandpark** [comment]
Fixed
