### ISSUE TITLE
[제안] 봇 아이디 오직 숫자만 가능하게 제안

### ISSUE THREAD

**Issue by MadeGOD** [koreanbots/v2-testing#107]
# 제안 내용
봇을 추가할에 아이디에 모르신 분들이 영문이나 한글을 적을수도 있으며 오직 아이디만 가능하게 만들면 좋을거 같습니다.
![Screenshot_20210517-182637](https://user-images.githubusercontent.com/63600304/118474333-8825d180-b73d-11eb-971b-4dfb25d2ce5e.png)

# 기대효과

 영문, 특문 등등이 안적히게 됩니다.

**Comment by wonderlandpark** [comment]
API에서도 검증해주며, 제출 전에도 오류 메세지를 표시하면서 검증해주기에 현재로써는 딱히 구현할 생각은 없습니다.
