### ISSUE TITLE
[제안] Beta API provides png, jpg, webp as well as svg format when providing images in the Widget feature

### ISSUE THREAD

**Issue by gunyu1019** [koreanbots/v2-testing#108]
# 제안 내용
![image](https://user-images.githubusercontent.com/16767890/118517184-f71d1d80-b771-11eb-87d6-20dc97a88a5f.png)
Widget 을 통하여 불러올 때 `.svg`로만 한정짓지 말고, `.png`, `.jpg`, `webp` 등의 다른 포맷도 지원해주세요.

# 기대효과
아무래도 `.svg`의 파일구조와 `.png`, `.jpg`, `.webp`는 서로 백터와 비트맵이 서로 다른 관계이여서 변환에 어려움을 끼칠수 있습니다. 이점을 완화해줄수 있는 효과를 불러올 수 있다고 봅니다.

**Comment by wonderlandpark** [comment]
Out of scope. 해당 사항은 라이브러리 등에서 지원하도록 합니다.

v2 릴리즈 이후에는 고려해보겠습니다만, 이번 릴리즈 때에는 포함하지 않겠습니다.
