### ISSUE TITLE
[버그] Captcha window goes out of the expected position

### ISSUE THREAD

**Issue by eunwoo1104** [koreanbots/v2-testing#110]
# 버그 설명
캡챠 칸이 원래 있어야 되는 부분이 아닌 윗부분으로 튀어오릅니다.

# 재현방법
 `새로운 봇 추가하기` 애서 새 봇을 추가하고 캡챠 진행을 시도합니다.

# 예상한 동작
캡챠 칸이 밑에 존재해야 합니다.

# 클라이언트 정보

- 브라우저(버전): Chrome 90.0.4430.212
- OS: Windows 10
- 기기: PC

# 발생되는 페이지

https://beta.koreanbots.dev/addbot

# 첨부파일
![image](https://user-images.githubusercontent.com/61371424/119232863-a63a6a00-bb61-11eb-97ee-c75091a327eb.png)

**Comment by wonderlandpark** [comment]
빨리 찾으셨네요..! 인지하고 있으며 고치는 중입니다
