### ISSUE TITLE
Markdown 이탤릭체가 적용되지 않음

### ISSUE THREAD

**Issue by JellyBrick** [koreanbots/v2-testing#80]
# 코드

```markdown
## _무료인가요?_

- blabla...

## _한국어를 지원하나요?_
```

# 예상되는 결과

![image](https://user-images.githubusercontent.com/16558115/117544482-9cdad900-b05c-11eb-9767-c69891520625.png)

# 실제 결과

![image](https://user-images.githubusercontent.com/16558115/117544488-a8c69b00-b05c-11eb-97bf-bed49c687049.png)

**Comment by wonderlandpark** [comment]
라이브러리가 underline 옵션을 사용하면 `_text_` 문법을 지원하지 않습니다 ㅜ
따라서 두 가지 선택지가 있습니다.

- <ins>밑줄</ins>의 문법(`__text__`)을 지원하고, *이탈릭체*는 `*text*`로만 지원한다. (현재)
- 밑줄을 지원하지 않고, _ 와 * 가 같은 역할을 합니다. (이탈릭체를 `_text_`와 `__text__`로 지원한다.

무엇이 더 좋을지 의견 부탁드립니다!

**Comment by simsimler** [comment]
밑줄을 사용하여 봇 소개를 작성하는 경우가 꽤 있고, 이탈릭체와 밑줄을 모두 지원하는 방향이 좋을 것 같습니다

**Comment by wonderlandpark** [comment]
일단 전자로 유지해두겠습니다.
