### ISSUE TITLE
유저 아바타 사진 해상도 조절

### ISSUE THREAD

**Issue by minibox24** [koreanbots/v2-testing#81]
모바일 모드에서 실제 이미지의 사이즈보다 유저(봇) 아바타 사진의 해상도가 작아 이미지가 깨져보이는 현상이 있습니다.

그래서 아바타 이미지의 해상도를 크게 조절하면 좋을 것 같습니다.

**Comment by gunyu1019** [comment]
모바일과 PC 버전에서 프로필 사진이 너무 크다고 느껴집니다. 컴퓨터에서는 화면이 좀 클 경우, 사진이 깨져보이는 것 처럼 보입니다. 사용자 아바타의 이미지를 띄었으면 좋겠습니다.
![image](https://user-images.githubusercontent.com/16767890/117545068-373c1c00-b05f-11eb-9275-5307e3856133.png)
해당 이미지는 제가 임의적으로 수정해본 값이며, border-radius를 110px, width를 250px로 선정해보았습니다. margin값은 모두 30px 씩 주었습니다. 단지 예시 일뿐, 반영해주셨으면 좋겠습니다.
