### ISSUE TITLE
봇의 서버수 기준 정렬

### ISSUE THREAD

**Issue by Seol7523** [koreanbots/v2-testing#82]
현재 봇의 정렬순서는 오직 하트 수를 기반으로 되어있습니다. 하트수도 봇의 수준을 평가할 수 있는 좋은 지표이지만 봇의 서버수도 하나의 지표가 될수 있을것 같습니다.

따라서

1. 봇을 볼때 서버 수를 기준으로 나열하거나
2. 서버수와 하트수를 종합적으로 이용해 나열하는 메뉴? 기능이 있었으면 좋겠습니다

+혹시 이미 있는데 제가 못 찾은것이라면 죄송합니다

**Comment by wonderlandpark** [comment]
현재 정렬 기준은 하트 수 정렬 후, 하트가 동일하다면 서버 수로 정렬하고 있습니다.

**Comment by Seol7523** [comment]
제가 말하고자 한것은 하트수를 제외시킨 오로지 서버수기준으로만 정렬하는 것입니다

**Comment by wonderlandpark** [comment]
현재 서버 수는 유저 업데이트에 의존하여 이렇게 된다면 순위 조작이 더 쉬워지는 문제가 발생할거 같습니다. 관리자 회의를 거쳐보도럭 하겠습니다.

**Comment by wonderlandpark** [comment]
추후 평점 등을 추가하는 등으로 개선해보겠습니다
