### ISSUE TITLE
스타일 개선사항들

### ISSUE THREAD

**Issue by frin0911** [koreanbots/v2-testing#83]
![image](https://user-images.githubusercontent.com/44210830/117545363-6d2dd000-b060-11eb-8029-c2dd435e03aa.png)

봇 정보 페이지 `디스코드 인증됨` 표시 줄바꿈

![image](https://user-images.githubusercontent.com/44210830/117545392-8f275280-b060-11eb-8b67-4bd893fe9f06.png)

버그 바운티 프로그램 내용 삐져나옴

**Comment by gunyu1019** [comment]
사용이나 여러가지 면에서는 많은 지장은 없으나 아래의 부분에서 메뉴의 부분을 저 확장시켜주었으면 좋겠습니다.

![image](https://user-images.githubusercontent.com/16767890/117545802-50929780-b062-11eb-9042-d18ae8c46273.png)
