### ISSUE TITLE
Left scrollbar displayed on developer page.

### ISSUE THREAD

**Issue by gunyu1019** [koreanbots/v2-testing#86]
## Describe
PC 환경에서, 개발자 페이지에서 아래와 같은 현상이 발생합니다.
![image](https://user-images.githubusercontent.com/16767890/117545629-8aaf6980-b061-11eb-8d72-b5d62f15f629.png)
좌측 부분에 이미 사이즈는 충분한데 필요하지 않는 스크롤바가 임의적으로 형성되는 것 같습니다.

## Page
https://beta.koreanbots.dev/developers/docs/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0

## Platform & Browse 
Windows 10 20H2, Chrome 90.0.4430.93(64비트)

**Comment by wonderlandpark** [comment]
CNR, Safari 14.0.3 / macOS Big Sur 11.3.1
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/31924512/117545919-ca2a8580-b062-11eb-9ab7-c5118492da9e.png">

**Comment by wonderlandpark** [comment]
CNR, Chrome 90.0.4430.93 / macOS Big Sur 11.3.1

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/31924512/117545948-f5ad7000-b062-11eb-8c03-1307f1302814.png">

**Comment by seojin200403** [comment]
![image](https://user-images.githubusercontent.com/51256209/117558762-f07c0f80-b0ba-11eb-916e-ee2d5cc091e7.png)

윈도우 버전 10.0.19042 빌드 19042
크롬 버전 90.0.4430.93(공식 빌드) (64비트)

**Comment by minibox24** [comment]
![image](https://user-images.githubusercontent.com/61264156/117558886-bf500f00-b0bb-11eb-948e-25e9913305c4.png)
Windows 10 20H2 (19042.928)
Chrome 90.0.4430.93
