### ISSUE TITLE
검색 시 키보드를 띄우면 레이아웃이 밀림

### ISSUE THREAD

**Issue by seojin200403** [koreanbots/v2-testing#89]
![Screenshot_20210509_013040_com.android.chrome.jpg](https://user-images.githubusercontent.com/51256209/117546758-006a0400-b067-11eb-90e0-be9dc7c907b8.jpg)

새로고침시까지 지속됨. 

크롬 90.0.4430.91
안드로이드 10

**Comment by wonderlandpark** [comment]
재현 가능하신 분 없나요?

**Comment by comjun04** [comment]
재현가능

Android 8
Chrome 90.0.4430.82

![Screenshot_2021-05-16-03-15-47.png](https://user-images.githubusercontent.com/30339539/118374063-13478000-b5f5-11eb-9734-0ac90bd08870.png)

**Comment by kijk2869** [comment]
재현 불가

Android 11
Chrome 90.0.4430.210

![Screenshot_20210516-184042_Chrome.png](https://user-images.githubusercontent.com/35522821/118392775-3a926180-b676-11eb-8389-b095c32a47e9.png)

**Comment by KeepSOBP** [comment]
재현 불가
Android 9
Chrome 90.0.4430.210

![Screenshot_20210516-190135_Chrome](https://user-images.githubusercontent.com/50764666/118393271-33b91e00-b679-11eb-830e-bd5068a155a1.jpg)

**Comment by wonderlandpark** [comment]
계속 재현되나요?

**Comment by injoon5** [comment]
버전이 살짝 낮은 안드로이드 크롬에서 발생하는듯 합니다. 

90.0.4430.210 이렇게 제일 끝 숫자가 좀 높으면 발생하지 않는데, 90.0.4430.82 혹은 90.0.4430.91 같은 비교적 낮은 버전에서 발생하는듯 합니다.

**Comment by wonderlandpark** [comment]
아직도 발생한다는 말씀이시죠?

**Comment by injoon5** [comment]
실제로 테스트를 하지는 않았으나, 클라이언트 문제인듯 하여 이슈를 남기게 되었습니다.

**Comment by wonderlandpark** [comment]
새로 커밋된 내용이 있어 혹시 고쳐졌는지 확인하고자 코맨트를 남겼습니다. 제가 재현되지가 않아서 이렇게 버그 픽스를 진행하는 점 양해부탁 드립니다.

**Comment by seojin200403** [comment]
그대로입니다.
