### ISSUE TITLE
하트 랭킹 9위, 10위 페이지에서 레이아웃이 깨짐

### ISSUE THREAD

**Issue by seojin200403** [koreanbots/v2-testing#91]
![Screenshot_20210509_014049_com.android.chrome.jpg](https://user-images.githubusercontent.com/51256209/117546931-dc5af280-b067-11eb-9629-491812997f3c.jpg)

![Screenshot_20210509_014152_com.android.chrome.jpg](https://user-images.githubusercontent.com/51256209/117546934-debd4c80-b067-11eb-8280-d4f0bd28bb97.jpg)

해당 페이지에서만 레이아웃이 우측으로 뚫고 나감.

안드로이드 10 / 크롬 90.0.4430.91

**Comment by kijk2869** [comment]
![image](https://user-images.githubusercontent.com/35522821/117591711-96d61c80-b170-11eb-9ce4-9b6ff8452e8a.png)

신뢰된 봇에서 재현 가능

**Comment by kijk2869** [comment]
![Uploading image.png…]()

동일한 크기에서 하트 랭킹은 재현되지 않음

**Comment by kijk2869** [comment]
![image](https://user-images.githubusercontent.com/35522821/117591738-b3725480-b170-11eb-8e35-2cffaa3b39a6.png)

동일한 크기에서 하트랭킹은 재현되지 않음

**Comment by kijk2869** [comment]
> ![Screenshot_20210509_014049_com.android.chrome.jpg](https://user-images.githubusercontent.com/51256209/117546931-dc5af280-b067-11eb-9629-491812997f3c.jpg)
> 
> ![Screenshot_20210509_014152_com.android.chrome.jpg](https://user-images.githubusercontent.com/51256209/117546934-debd4c80-b067-11eb-8280-d4f0bd28bb97.jpg)
> 
> 해당 페이지에서만 레이아웃이 우측으로 뚫고 나감.
> 
> 안드로이드 10 / 크롬 90.0.4430.91

폰 기종 첨부 부탁드립니다.

**Comment by seojin200403** [comment]
> @seojin200403
> 
> 폰 기종 첨부 부탁드립니다.

모델명 JNY-LX2
해상도 2310 × 1080

**Comment by kijk2869** [comment]
가로 크기 340px 이하부터 재현

**Comment by wonderlandpark** [comment]
https://user-images.githubusercontent.com/31924512/117664451-befb6500-b1dc-11eb-9b6e-8cb3195bb8ba.mov

저는 재현이 불가한데 혹시 다른 조건이 있을까요

**Comment by wonderlandpark** [comment]
@seojin200403 혹시 영상으로 녹화해주실 수 있나요?

**Comment by wonderlandpark** [comment]
재현 되나요?

**Comment by wonderlandpark** [comment]
재현이 불가한 관계로 이슈를 닫겠습니다
