### ISSUE TITLE
Bot card overlaps search history

### ISSUE THREAD

**Issue by eunwoo1104** [koreanbots/v2-testing#94]
![image](https://user-images.githubusercontent.com/61371424/117547197-52138e00-b069-11eb-8794-d7a2a7f9d729.png)
최근 검색어 목록이 너무 길 경우 봇 카드가 최근 검색어 창을 일부분 덮습니다. 최근 검색어가 봇 카드를 덮도록 하는 것이 좋을 것 같습니다.

**Comment by wonderlandpark** [comment]
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/31924512/117557868-a42cd180-b0b2-11eb-8329-f0dc75229b3c.png">

**Comment by wonderlandpark** [comment]
광고는 계속 위에 표시됨
