### ISSUE TITLE
Permission calculator returns -2147483648 if "Use Slash Commands" checked

### ISSUE THREAD

**Issue by despenser08** [koreanbots/v2-testing#95]
Expected: Should return `2147483648`

Actual Result: It returns `-2147483648`

![Screenshot 2021-05-08 at 15-14-34 봇 초대링크 생성기 - 한국 디스코드봇 리스트](https://user-images.githubusercontent.com/50207925/117552312-20220d80-b010-11eb-8f30-eac68262a085.png)

**Comment by kijk2869** [comment]
`-2147483648` also works as `2147483648`

Not a bug.
