### ISSUE TITLE
일부 봇 카테고리가 404로 표시됨.

### ISSUE THREAD

**Issue by Krchip** [koreanbots/v2-testing#96]
카테고리 더보기를 통해 존재하는 배틀그라운드, 리그오브레전드 등의 카테고리가 404로 표시됨.

![image](https://user-images.githubusercontent.com/35456778/117557924-303ef900-b0b3-11eb-928f-dc625fffeb8d.png)

**Comment by wonderlandpark** [comment]
NAB, 해당 카테고리에 존재하는 봇이 없어서 발생하는 문제입니다.
