### ISSUE TITLE
[버그] Overflow phenomenon in the authority calculator.

### ISSUE THREAD

**Issue by gunyu1019** [koreanbots/v2-testing#98]
# 버그 설명
권한 계산기에서 Slash Command에게 권한을 부여했을 경우 값이 오버플로우 되는 현상이 발견되었습니다.

# 재현방법
생성기에 재현된 결과 값과 링크에 포함된 퍼머션 값이 -2147483648가 리턴됩니다.

# 예상한 동작
리턴된 퍼머션의 값이 2147483648가 리턴되어야만 합니다.

# 클라이언트 정보

- 브라우저(버전): Chrome
- OS: Windows 10 20H2

# 발생되는 페이지

https://beta.koreanbots.dev/calculator

# 첨부 파일
![image](https://user-images.githubusercontent.com/16767890/117563052-37c7c780-b0de-11eb-9caa-a1ddea7a7496.png)

**Comment by wonderlandpark** [comment]
Dupe of #95
